spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./target/H2DB/test-LearnHub;AUTO_SERVER=TRUE
    username: sa
    password: pass
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2
